-- ===================================================================================================================================
-- STEP 2. FILL THE TABLE WITH THE TEST DATAS.
CREATE TABLE AUTHOR (
    AUTHOR_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME CHAR (30),
    BIRTH_YEAR DATE,
    DEATH_YEAR DATE
);

SELECT INTO AUTHOR (AUTHOR_ID, AUTHOR_NAME, BIRTH_YEAR, DEATH_YEAR)
VALUE 
(1, 'HENRY WHITE', '1999-10-20', NULL),
(2, 'ETHAN MORE', '1952-01-30', '2020-12-04'), 
(3, 'BARAK OBAMA', '1961-08-04', NULL),
(4, 'DONALD TRAMP', '1946-06-14', NULL),
(5, 'JOE BYDEN', '1942-11-20', NULL);

CREATE TABLE BOOK (
    BOOK_ID SERIAL PRIMARY KEY,
	AUTHOR_ID INTEGER REFERENCES AUTHOR(AUTHOR_ID),
    TITLE CHAR (30),
    PUBLISH_YEAR DATE,
    PUBLISHING_HOUSE CHAR (30),
    RATING REAL
);

SELECT INTO BOOK (BOOK_ID, AUTHOR_ID, TITLE, PUBLISH_YEAR, PUBLISHING_HOUSE, RATING)
VALUE 
(1, 34, 'OVER THE ABOVE', 2014-01-14, 'BROWN AND COMPANY', 2.1),
(2, 61, 'ELEGANCE OF THE HEDGEHOG', 2015-04-04, 'ABC ATTICUS', 3.5),
(3, 12, 'OVER THE ABOVE', 1987, 'BROWN AND COMPANY', 2.1),
(4, 67, 'DOG`S HEART', 1987, 'HARCOURT', 3.6),
(5, 45, 'GOLDEN CALF', 1968, 'EKSMO', 5.4);

CREATE TABLE ADAPTATION (
    BOOK_ID SERIAL PRIMARY KEY,
    ADAPTATION_TYPE CHAR (30),
    ADAPTATION_TITLE CHAR (30),
    RELEASE_YEAR DATE,
    RATING REAL
);

SELECT INTO ADAPTATION (BOOK_ID, ADAPTATION_TYPE, ADAPTATION_TITLE, RELEASE_YEAR, RATING)
VALUE
(1, 'MOVIE', 'GENTLEMEN', 2020-01-01, 8.5)
(2, 'MOVIE', 'MINARI', 2020-02-11, 6.9)
(3, 'MOVIE', 'DOCTOR LISA', 2020-10-22, 8.1)
(4, 'MOVIE', 'KALASHNIKOV', 2020-02-20, 7.5)
(5, 'MOVIE', 'TOMIRIS', 2020-09-25, 8.3)

-- STEP 3. COMPLETE TASKS

-- Q-1.
SELECT AUTHOR_NAME, TITLE 
FROM AUTHOR 
RIGHT JOIN BOOK 
ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID;
-- Q-2.
SELECT AUTHOR_NAME, TITLE, PUBLISH_YEAR 
FROM AUTHOR 
RIGHT JOIN BOOK 
ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
WHERE BOOK.PUBLISH_YEAR > '2005';
-- Q-3.
SELECT BOOK.TITLE, BOOK.PUBLISH_HOUSE, ADAPTATION.TITLE, ADAPTATION.ADAP_TYPE 
FROM BOOK 
INNER JOIN ADAPTATION 
ON BOOK.BOOK_ID = ADAPTATION.BOOK_ID;
-- Q-4.
SELECT TITLE, PUBLISH_YEAR
FROM BOOK
LEFT JOIN BOOK_REVIEW
ON BOOK.BOOK_ID = BOOK_REVIEW.BOOK_ID
WHERE BOOK_REVIEW.BOOK_ID IS NULL;
-- Q-5.
SELECT B.BOOK_ID, B.TITLE, A.AUTHOR_NAME 
FROM BOOK AS B
LEFT JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE A.PUBLISH_YEAR (1900);
-- Q-6.
SELECT TITLE, RATING 
FROM AUTHOR 
INNER JOIN BOOK 
ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID 
WHERE AUTHOR.DEATH_YEAR IS NOT NULL
-- Q-7.
SELECT B.TITLE AS TITLE_OF_BOOK, A.TITLE AS TITLE_OF_ADAPTATION, A.RELEASE_YEAR
FROM BOOK AS B
LEFT JOIN ADAPTAION AS A
ON B.BOOK_ID = A.BOOK_ID
-- Q-8.
TITLE_OF_BOOK, A.TITLE AS TITLE_OF_ADAPTATION, A.RELEASE_YEAR
FROM BOOK AS B
LEFT JOIN ADAPTAION AS A
ON B.BOOK_ID = A.BOOK_ID